name: SFCore
version: 1.0.0
main: dev.sfcore.SFCorePlugin
api-version: '1.21'
authors: [LujuZk]
description: SpiritForge central stats manager
load: STARTUP

commands:
  sfcore:
    description: SFCore admin commands
    usage: /sfcore <test|stats> [args...]
    permission: sfcore.admin

permissions:
  sfcore.admin:
    description: Access to SFCore admin commands
    default: op
