name: SFCrafting
version: 1.0.0
main: dev.sfcrafting.SFCraftingPlugin
api-version: '1.21'
depend: [SFCore]
softdepend: [Oraxen, SkillTreePlugin, SFCharacter]
authors: [LujuZk]
description: SpiritForge crafting and forging plugin

commands:
  sfcrafting:
    description: SFCrafting admin commands
    usage: /sfcrafting give <oraxen_id|material:id> [cantidad] [rareza] | /sfcrafting givebow <tipo> <madera> <rareza_madera> <metal> <rareza_metal> [cantidad] [rareza_final]
    permission: sfcrafting.admin
    aliases: [cforge]
  recetas:
    description: Abre el recetario de forja
    usage: /recetas
    permission: sfcrafting.recetario
    aliases: [recetario, recipes]

permissions:
  sfcrafting.admin:
    description: Access to SFCrafting admin commands
    default: op
  sfcrafting.recetario:
    description: Acceso al recetario
    default: true
